"""Core of the local Claude Code / Claude Desktop data export.

This module gathers the export *logic* (path resolution per operating system,
building the ZIP archive). The command-line interface lives in
:mod:`ai_tools.cli.claude_export`.

Config locations differ by platform. They can be overridden with environment
variables:

- ``CLAUDE_CODE_DIR``    : Claude Code folder (default: ``~/.claude``)
- ``CLAUDE_DESKTOP_DIR`` : Claude Desktop folder (default per OS, see below)
"""

from __future__ import annotations

import os
import platform
import zipfile
from pathlib import Path

# File never included in the export: it holds the Anthropic/MCP OAuth tokens.
EXCLUDED_FILENAMES = {".credentials.json"}


def claude_code_dir() -> Path:
    """Claude Code data folder.

    Identical on all platforms (``~/.claude``), overridable via the
    ``CLAUDE_CODE_DIR`` environment variable.
    """
    env = os.environ.get("CLAUDE_CODE_DIR")
    return Path(env).expanduser() if env else Path.home() / ".claude"


def claude_desktop_dir() -> Path:
    """Config folder for the Claude Desktop application.

    Default location per OS:

    - Windows : ``%APPDATA%\\Claude``
    - macOS   : ``~/Library/Application Support/Claude``
    - Linux   : ``~/.config/Claude``

    Overridable via the ``CLAUDE_DESKTOP_DIR`` environment variable.
    """
    env = os.environ.get("CLAUDE_DESKTOP_DIR")
    if env:
        return Path(env).expanduser()

    system = platform.system()
    if system == "Windows":
        appdata = os.environ.get("APPDATA")
        base = Path(appdata) if appdata else Path.home() / "AppData" / "Roaming"
        return base / "Claude"
    if system == "Darwin":
        return Path.home() / "Library" / "Application Support" / "Claude"
    return Path.home() / ".config" / "Claude"


def build_sources() -> list[tuple[Path, str]]:
    """Builds the list of ``(source on disk, path inside the ZIP)`` to export."""
    code = claude_code_dir()
    desktop = claude_desktop_dir()
    documents = Path.home() / "Documents" / ".claude" / "settings.local.json"

    return [
        (code / "projects", "claude_code/projects"),
        (code / "plans", "claude_code/plans"),
        (code / "settings.json", "claude_code/settings.json"),
        (code / "settings.local.json", "claude_code/settings.local.json"),
        (code / "history.jsonl", "claude_code/history.jsonl"),
        (code / "backups", "claude_code/backups"),
        (code / "shell-snapshots", "claude_code/shell-snapshots"),
        (code / "paste-cache", "claude_code/paste-cache"),
        (desktop / "config.json", "claude_desktop/config.json"),
        (desktop / "claude_desktop_config.json", "claude_desktop/claude_desktop_config.json"),
        (desktop / "logs", "claude_desktop/logs"),
        (documents, "claude_desktop/documents_settings.local.json"),
    ]


README_TEMPLATE = """# Claude Data Export — {date}

## Contents of this ZIP

### claude_code/
- `projects/`       : Full history of all Claude Code sessions
- `plans/`          : Session planning files
- `settings.json`   : Claude Code preferences (language, model, effort)
- `settings.local.json` : Local permissions (pacman, system paths)
- `history.jsonl`   : Chronological command history
- `backups/`        : Configuration backups
- `shell-snapshots/`: Shell environment snapshots
- `paste-cache/`    : Clipboard cache

### claude_desktop/
- `config.json`                    : Desktop app configuration (language, theme, display)
- `claude_desktop_config.json`     : Approved folders, permissions, modes
- `logs/`                          : Application logs (main.log, ssh.log, etc.)
- `documents_settings.local.json`  : Documents folder permissions

## What is NOT in this ZIP

- `.credentials.json` : Anthropic + MCP OAuth tokens (excluded for security)
- Binary caches automatically regenerated by the app
- claude.ai conversations (web interface): stored on Anthropic's servers

## Exporting claude.ai conversations (web interface)

To retrieve the conversation history from the web interface:
1. Go to https://privacy.anthropic.com
2. "Download my data" section (GDPR/CCPA right)
3. Turnaround: 24-72h, export sent by email
"""


def _is_excluded(path: Path) -> bool:
    return path.name in EXCLUDED_FILENAMES


def add_path(
    archive: zipfile.ZipFile | None,
    source: Path,
    dest: str,
    dry_run: bool,
) -> int:
    """Adds *source* (file or folder) to the archive under the *dest* prefix.

    Returns the number of files added. In *dry_run* mode, ``archive`` may be
    ``None``: nothing is written, only the count is returned.
    """
    if not source.exists():
        print(f"  [SKIP] {source}  (not found)")
        return 0

    count = 0
    if source.is_file():
        if _is_excluded(source):
            print(f"  [SKIP] {source}  (excluded for security)")
            return 0
        if not dry_run:
            archive.write(source, dest)
        count = 1
    else:
        for file in sorted(source.rglob("*")):
            if not file.is_file() or _is_excluded(file):
                continue
            # ZIP entry names must use forward slashes; as_posix() keeps them
            # portable on Windows (where relative_to() would yield backslashes).
            arc_name = f"{dest}/{file.relative_to(source).as_posix()}"
            if not dry_run:
                archive.write(file, arc_name)
            count += 1

    print(f"  [OK]   {source}  →  {dest}  ({count} file(s))")
    return count


def export(output: Path, today: str, dry_run: bool = False) -> int:
    """Exports all sources into the *output* ZIP.

    *today* is a ``YYYYMMDD`` string used in the embedded README.
    Returns the total number of exported files.
    """
    sources = build_sources()

    if dry_run:
        for source, dest in sources:
            add_path(None, source, dest, dry_run=True)
        return 0

    total = 0
    with zipfile.ZipFile(output, "w", zipfile.ZIP_DEFLATED, compresslevel=6) as archive:
        archive.writestr("README.md", README_TEMPLATE.format(date=today))
        for source, dest in sources:
            total += add_path(archive, source, dest, dry_run=False)
    return total
